### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by colindaven** [Bgi-LUSH/LUSH-DNASeq-pipeline#1]
Hello,

this looks interesting, but unfortunately no license is present at the moment, which indicates all rights reserved - no usage by anyone. Do you plan to add a license ? Thanks.

**Comment by Bgi-LUSH** [comment]
Thank you for your interest in LUSH. The LUSH toolkit is accessible at no cost for non-commercial purposes, and we have updated the Git repository accordingly.
