### ISSUE TITLE
lush_aligner

### ISSUE THREAD

**Issue by lihaicheng7003** [Bgi-LUSH/LUSH-DNASeq-pipeline#8]
no file `./bin/LUSH_toolkit-Aligner/lush_aligner`,

**Comment by Bgi-LUSH** [comment]
Hello, thank you for your reply. We have updated the version of lush_aligner, changed the binary file lush_aligner to lush_Aligner1_share, and also changed the parameter mode.We have update the readme and shell files, please check it out. Please let me know if you have any questions.
